In [105]:
# Importamos las librerías tradicionales
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Importamos las librerías relacionadas con json
import json

# Importamos las librerías relacionadas con llamadas HTTPS
import requests

In [106]:
url = "https://jsonplaceholder.typicode.com/users"

# Hacemos un llamado https de tipo get
respuesta = requests.get(url)
texto = respuesta.text

# Armamos el DataFrame
jsondata = json.loads(texto)
df = pd.DataFrame.from_dict(jsondata)
df.head()

# Seteamos el índice para que quede mejor
df = df.set_index('id')
df.head()

,name,username,email,address,phone,website,company
id,,,,,,,
1,Leanne Graham,Bret,Sincere@april.biz,"{'street': 'Kulas Light', 'suite': 'Apt. 556',...",1-770-736-8031 x56442,hildegard.org,"{'name': 'Romaguera-Crona', 'catchPhrase': 'Mu..."
2,Ervin Howell,Antonette,Shanna@melissa.tv,"{'street': 'Victor Plains', 'suite': 'Suite 87...",010-692-6593 x09125,anastasia.net,"{'name': 'Deckow-Crist', 'catchPhrase': 'Proac..."
3,Clementine Bauch,Samantha,Nathan@yesenia.net,"{'street': 'Douglas Extension', 'suite': 'Suit...",1-463-123-4447,ramiro.info,"{'name': 'Romaguera-Jacobson', 'catchPhrase': ..."
4,Patricia Lebsack,Karianne,Julianne.OConner@kory.org,"{'street': 'Hoeger Mall', 'suite': 'Apt. 692',...",493-170-9623 x156,kale.biz,"{'name': 'Robel-Corkery', 'catchPhrase': 'Mult..."
5,Chelsey Dietrich,Kamren,Lucio_Hettinger@annie.ca,"{'street': 'Skiles Walks', 'suite': 'Suite 351...",(254)954-1289,demarco.info,"{'name': 'Keebler LLC', 'catchPhrase': 'User-c..."

Pero hay un problema, los datos de las columnas address y company son diccionarios en si mismos.
Entonces, usamos ciclos for para generar dos dataframes separados con las direcciones y las compañías.
Luego, los joineamos con un pd.concat

In [122]:
# Arrancamos por las direcciones
address_dict = pd.Series.to_dict(df['address'])

In [123]:
users_ids = []
address_df = pd.DataFrame(columns = ['id', 'street', 'suite', 'city', 'zipcode', 'lat', 'long'])
address_df

Empty DataFrame
Columns: [id, street, suite, city, zipcode, lat, long]
Index: []

In [124]:
for user_id, d in address_dict.items(): 
    address_df = address_df.append({'id' : user_id,
                            'street' : d['street'], 
                            'suite' : d['suite'],
                            'city' : d['city'],
                            'zipcode' : d['zipcode'],
                            'lat' : d['geo']['lat'],
                            'long' : d['geo']['lat']}, 
                            ignore_index = True)

In [125]:
address_df = address_df.set_index('id')
address_df

,street,suite,city,zipcode,lat,long
id,,,,,,
1,Kulas Light,Apt. 556,Gwenborough,92998-3874,-37.3159,-37.3159
2,Victor Plains,Suite 879,Wisokyburgh,90566-7771,-43.9509,-43.9509
3,Douglas Extension,Suite 847,McKenziehaven,59590-4157,-68.6102,-68.6102
4,Hoeger Mall,Apt. 692,South Elvis,53919-4257,29.4572,29.4572
5,Skiles Walks,Suite 351,Roscoeview,33263,-31.8129,-31.8129
6,Norberto Crossing,Apt. 950,South Christy,23505-1337,-71.4197,-71.4197
7,Rex Trail,Suite 280,Howemouth,58804-1099,24.8918,24.8918
8,Ellsworth Summit,Suite 729,Aliyaview,45169,-14.3990,-14.3990
9,Dayna Park,Suite 449,Bartholomebury,76495-3109,24.6463,24.6463
10,Kattie Turnpike,Suite 198,Lebsackbury,31428-2261,-38.2386,-38.2386

In [126]:
# Continuamos con las compañías
company_dict = pd.Series.to_dict(df['company'])
company_dict

{1: {'name': 'Romaguera-Crona',
  'catchPhrase': 'Multi-layered client-server neural-net',
  'bs': 'harness real-time e-markets'},
 2: {'name': 'Deckow-Crist',
  'catchPhrase': 'Proactive didactic contingency',
  'bs': 'synergize scalable supply-chains'},
 3: {'name': 'Romaguera-Jacobson',
  'catchPhrase': 'Face to face bifurcated interface',
  'bs': 'e-enable strategic applications'},
 4: {'name': 'Robel-Corkery',
  'catchPhrase': 'Multi-tiered zero tolerance productivity',
  'bs': 'transition cutting-edge web services'},
 5: {'name': 'Keebler LLC',
  'catchPhrase': 'User-centric fault-tolerant solution',
  'bs': 'revolutionize end-to-end systems'},
 6: {'name': 'Considine-Lockman',
  'catchPhrase': 'Synchronised bottom-line interface',
  'bs': 'e-enable innovative applications'},
 7: {'name': 'Johns Group',
  'catchPhrase': 'Configurable multimedia task-force',
  'bs': 'generate enterprise e-tailers'},
 8: {'name': 'Abernathy Group',
  'catchPhrase': 'Implemented secondary concept',
  'bs': 'e-enable extensible e-tailers'},
 9: {'name': 'Yost and Sons',
  'catchPhrase': 'Switchable contextually-based project',
  'bs': 'aggregate real-time technologies'},
 10: {'name': 'Hoeger LLC',
  'catchPhrase': 'Centralized empowering task-force',
  'bs': 'target end-to-end models'}}

In [127]:
users_ids = []
company_df = pd.DataFrame(columns = ['id', 'name', 'catchphrase', 'bs'])
company_df

Empty DataFrame
Columns: [id, name, catchphrase, bs]
Index: []

In [128]:
for user_id, d in company_dict.items():
    company_df = company_df.append({'id' : user_id,
                                    'name' : d['name'],
                                    'catchphrase' : d['catchPhrase'],
                                    'bs' : d['bs']},
                                    ignore_index = True)
company_df = company_df.set_index('id')
company_df

,name,catchphrase,bs
id,,,
1,Romaguera-Crona,Multi-layered client-server neural-net,harness real-time e-markets
2,Deckow-Crist,Proactive didactic contingency,synergize scalable supply-chains
3,Romaguera-Jacobson,Face to face bifurcated interface,e-enable strategic applications
4,Robel-Corkery,Multi-tiered zero tolerance productivity,transition cutting-edge web services
5,Keebler LLC,User-centric fault-tolerant solution,revolutionize end-to-end systems
6,Considine-Lockman,Synchronised bottom-line interface,e-enable innovative applications
7,Johns Group,Configurable multimedia task-force,generate enterprise e-tailers
8,Abernathy Group,Implemented secondary concept,e-enable extensible e-tailers
9,Yost and Sons,Switchable contextually-based project,aggregate real-time technologies
10,Hoeger LLC,Centralized empowering task-force,target end-to-end models

In [131]:
# Ahora ya tenemos los tres dataframes, coancatenamos
dataframe_final = pd.concat([df, address_df, company_df], axis = 1)
dataframe_final
dataframe_final.drop(['address', 'company'], axis = 1)

,name,username,email,phone,website,street,suite,city,zipcode,lat,long,name,catchphrase,bs
id,,,,,,,,,,,,,,
1,Leanne Graham,Bret,Sincere@april.biz,1-770-736-8031 x56442,hildegard.org,Kulas Light,Apt. 556,Gwenborough,92998-3874,-37.3159,-37.3159,Romaguera-Crona,Multi-layered client-server neural-net,harness real-time e-markets
2,Ervin Howell,Antonette,Shanna@melissa.tv,010-692-6593 x09125,anastasia.net,Victor Plains,Suite 879,Wisokyburgh,90566-7771,-43.9509,-43.9509,Deckow-Crist,Proactive didactic contingency,synergize scalable supply-chains
3,Clementine Bauch,Samantha,Nathan@yesenia.net,1-463-123-4447,ramiro.info,Douglas Extension,Suite 847,McKenziehaven,59590-4157,-68.6102,-68.6102,Romaguera-Jacobson,Face to face bifurcated interface,e-enable strategic applications
4,Patricia Lebsack,Karianne,Julianne.OConner@kory.org,493-170-9623 x156,kale.biz,Hoeger Mall,Apt. 692,South Elvis,53919-4257,29.4572,29.4572,Robel-Corkery,Multi-tiered zero tolerance productivity,transition cutting-edge web services
5,Chelsey Dietrich,Kamren,Lucio_Hettinger@annie.ca,(254)954-1289,demarco.info,Skiles Walks,Suite 351,Roscoeview,33263,-31.8129,-31.8129,Keebler LLC,User-centric fault-tolerant solution,revolutionize end-to-end systems
6,Mrs. Dennis Schulist,Leopoldo_Corkery,Karley_Dach@jasper.info,1-477-935-8478 x6430,ola.org,Norberto Crossing,Apt. 950,South Christy,23505-1337,-71.4197,-71.4197,Considine-Lockman,Synchronised bottom-line interface,e-enable innovative applications
7,Kurtis Weissnat,Elwyn.Skiles,Telly.Hoeger@billy.biz,210.067.6132,elvis.io,Rex Trail,Suite 280,Howemouth,58804-1099,24.8918,24.8918,Johns Group,Configurable multimedia task-force,generate enterprise e-tailers
8,Nicholas Runolfsdottir V,Maxime_Nienow,Sherwood@rosamond.me,586.493.6943 x140,jacynthe.com,Ellsworth Summit,Suite 729,Aliyaview,45169,-14.3990,-14.3990,Abernathy Group,Implemented secondary concept,e-enable extensible e-tailers
9,Glenna Reichert,Delphine,Chaim_McDermott@dana.io,(775)976-6794 x41206,conrad.com,Dayna Park,Suite 449,Bartholomebury,76495-3109,24.6463,24.6463,Yost and Sons,Switchable contextually-based project,aggregate real-time technologies
10,Clementina DuBuque,Moriah.Stanton,Rey.Padberg@karina.biz,024-648-3804,ambrose.net,Kattie Turnpike,Suite 198,Lebsackbury,31428-2261,-38.2386,-38.2386,Hoeger LLC,Centralized empowering task-force,target end-to-end models